export const PROGRAM_VENDOR_EXPORT_KINDS = [
  "CHATGPT_USERS_CSV",
  "CHATGPT_USER_ANALYTICS",
  "CHATGPT_GPTS_CSV",
  "CHATGPT_GPT_ANALYTICS",
  "CHATGPT_PROJECTS_CSV",
  "CHATGPT_PROJECT_ANALYTICS",
  "CHATGPT_IMPACT_SURVEY_CSV",
  "CHATGPT_SURVEY_ANALYTICS",
  "UNIFIED_CREDITS_COSTS",
  "UNIFIED_CREDITS_SYNC_STATE",
  "WORKSPACE_ANALYTICS_SYNC_STATE",
  "CODEX_WORKSPACE_JSON",
  "CODEX_SESSIONS_JSON",
  "CODEX_CODE_REVIEW_JSON",
  "CODEX_CODE_REVIEW_RESPONSES_JSON",
  "CURSOR_ANALYTICS_TEAM_CSV",
] as const;

export type ProgramVendorExportKind = (typeof PROGRAM_VENDOR_EXPORT_KINDS)[number];

export function isProgramVendorExportKind(s: string): s is ProgramVendorExportKind {
  return (PROGRAM_VENDOR_EXPORT_KINDS as readonly string[]).includes(s);
}
